---
title: Sophie Dewey
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    image: 
    video: 
    company: 
    runtime: 
    director: 
    producers: 
    role: 
    is-featured: 
url: http://sophiedewey.com
permalink: pretty
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
exclude:
- bower_components
description: London-based freelance producer specialising in online content, commercials
  and music videos
domain: http://sophiedewey.com
company: Sophie Dewey
email: info@sophiedewey.com
facebook: 
instagram: sophielouisedewey
twitter: 
imdb: 
vimeo: 
linkedin: 
googleplus: 
google_site_verification: JsKZJjAYl-cQI2L2kbGIVacYhNRlYoZTzTUpHREVCjU
analytics: UA-77269752-1
logo: "/assets/img/layout/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
